---
# tasks file for roles/frontend
- name: Get and install nodejs repo
  shell: " curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - "

- name: Install nodejs
  apt:
    name: nodejs
    state: latest

- name: create www-data user
  user:
    name: www-data
    create_home: no
    shell: /sbin/nologin

- name: Creates /var/www-data directory
  file:
    path: /var/www-data
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Download frontend tgz from Nexus
  get_url:
    url: "https://nexus.praktikum-services.tech/repository/std-028-038-frontend/{{frontend_version}}/sausage-store-{{frontend_version}}.tar.gz"
    dest: "/var/www-data/sausage-store.tar.gz"
    owner: www-data
    group: www-data
    username: "{{username}}"
    password: "{{password}}"

- name: Unarchive a file 
  ansible.builtin.unarchive:
    src: /var/www-data/sausage-store.tar.gz
    dest: /var/www-data
    owner: www-data
    remote_src: yes

- name: Delete tar gz file
  file:
    state: absent
    path: /var/www-data/sausage-store.tar.gz

- name: Install http-server
  command: npm install http-server -g

- name: copy sausage-store-frontend.service to systemd folder
  template:
    src: sausage-store-frontend.service.j2
    dest: /etc/systemd/system/sausage-store-frontend.service    

- name: http-server can run from www-data user
  command: sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/node

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start sausage-store-frontend.service
  service:
    name: sausage-store-frontend
    state: restarted
