apiVersion: v1
data:
  default.conf: |
    server {

      listen 80;

      location / {
        root   /app/frontend;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }

      location /api {
          proxy_pass http://backend:8080;
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-conf