apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsidXNlcm5hbWUiOiJzdGQtMDI4LTM4IiwicGFzc3dvcmQiOiI4YWY5akUzUSIsImVtYWlsIjoibXllbWFpbEB5YS5ydSIsImF1dGgiOiJjM1JrTFRBeU9DMHpPRG80WVdZNWFrVXpVUT09In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: myregistrykey
type: kubernetes.io/dockerconfigjson
