apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-report
  name: backend-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend-report
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - image: gitlab.praktikum-services.ru:5050/std-028-38/sausage-store/sausage-backend-report:latest
        name: backend-report
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-uri-secret
              key: SPRING_DATA_MONGODB_URI
        - name: PORT
          value: "8080"
        - name: REPORT_PATH
          value: /var/www-data/htdocs
          